/*!
This is automatically generated file. 
DO NOT EDIT THIS FILE. 
\author		Shun Moriya 
\copyright	2024- Shun Moriya 
All Rights Reserved.
*/
#pragma once
#if !defined(DRAW_LOTS_PLUGIN_INFORMATION_DETECTED)
#define DRAW_LOTS_PLUGIN_INFORMATION_DETECTED
#define DRAW_LOTS_PLUGIN_FILE_VERSION 3
#define DRAW_LOTS_PLUGIN_VERSION 1
#define DRAW_LOTS_PLUGIN_VERSION_NAME "0.0.0"
#define DRAW_LOTS_PLUGIN_FRIENDLY_NAME "DrawLots"
#define DRAW_LOTS_PLUGIN_DESCRIPTION "Lottery that can designate winning weights"
#define DRAW_LOTS_PLUGIN_DOCS_URL "https://github.com/shun126/DrawLots/wiki"
#define DRAW_LOTS_PLUGIN_SUPPORT_URL "https://github.com/shun126/DrawLots/discussions/"
#define DRAW_LOTS_PLUGIN_BETA_VERSION false
#endif
