/* 
This is automatically generated file. 
DO NOT EDIT THIS FILE. 
\author		Shun Moriya 
\copyright	2024- Shun Moriya 
All Rights Reserved. 
*/ 
#pragma once 
#if !defined(JENKINS_BUILD_DETECTED) 
#define JENKINS_BUILD_DETECTED 
#define JENKINS_BUILD_NUMBER 0
#define JENKINS_BUILD_ID 0
#define JENKINS_NODE_NAME "" 
#define JENKINS_JOB_NAME "DrawLotsPlugin" 
#define JENKINS_BUILD_TAG ""
#define JENKINS_JOB_TAG "" 
#define JENKINS_GIT_BRANCH "" 
#define JENKINS_GIT_COMMIT "" 
#define JENKINS_UUID "b5598d98-d1ec-2e27-dced-64942e042f95" 
#define JENKINS_LICENSE "MIT" 
#define JENKINS_FOR_DEVELOP 1
#define JENKINS_FOR_RELEASE 0
#endif 
