/*!
This is automatically generated file. 
DO NOT EDIT THIS FILE. 
\author		Shun Moriya 
\copyright	2024- Shun Moriya 
All Rights Reserved.
*/
#pragma once
#if !defined(DUNGENERATOR_PLUGIN_INFOMATION_DETECTED)
#define DUNGENERATOR_PLUGIN_INFOMATION_DETECTED
#define DUNGENERATOR_PLUGIN_FILE_VERSION 3
#define DUNGENERATOR_PLUGIN_VERSION 1
#define DUNGENERATOR_PLUGIN_VERSION_NAME "1.0.0"
#define DUNGENERATOR_PLUGIN_FRIENDLY_NAME "DrawLots"
#define DUNGENERATOR_PLUGIN_DESCRIPTION "Lottery that can designate winning weights"
#define DUNGENERATOR_PLUGIN_DOCS_URL "https://github.com/shun126/DrawLots/wiki"
#define DUNGENERATOR_PLUGIN_SUPPORT_URL "https://github.com/shun126/DrawLots/discussions/"
#define DUNGENERATOR_PLUGIN_BETA_VERSION false
#endif
